name: example_workflow
on:
 push:
  branches:
  - react_app_deploy
jobs:
 build_job:
  name: build_job
  runs-on: ubuntu-latest
  steps:
   - name: build_job-download
     uses: actions/checkout@v2
   - name: build_job-start
     run: npm install; npm run build
   - name: build_job-upload
     uses: actions/upload-artifact@v2
     with:
      name: build_job-upload
      path: ./build
 deploy_job:
  runs-on: ubuntu-latest
  needs: build_job
  steps:
    - name: deploy_job-download
      uses: actions/download-artifact@v2
      with: 
        name: build_job-upload
    - name: deploy_job-surge
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: tonomolla6.surge.sh
        project: .
        login: ${{secrets.SURGE_EMAIL }}
        token: ${{secrets.SURGE_TOKEN }}