name: main_workflow
on:
  push:
    branches:
      - nodejs_linter_job

jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: 
          - 12.x
          - 10.x
      - name: Linter execution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true