name: main_workflow
on:
  push:
    branches:
      - nodejs_environment_job

jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Linter execution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: nodejs_nodeversions_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    name: test-execution
    runs-on: ubuntu-latest
    needs: linter-execution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm install jest; npm test
  environment_test_execution:
    name: environment_test_execution
    runs-on: ubuntu-latest
    needs: [linter-execution, test-execution]
    env: 
      DESTINATION_PERSON: "2DAW"
    steps:
      - name: github-actions-hello
        uses: adeloyedeji/github-actions-hello@v1.0
        with: 
          who-to-greet: "${{Env.DESTINATION_PERSON}}"