name: send_telegram_workflow
on:
  push:
    branches:
      - send_telegram_action
jobs:
  envio_mensaje:
    name: envio_mensaje
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run action
        uses: ./.github/actions/send_telegram_msg
        with:
          name: "Tono"
          id_chat: ${{ secrets.TELEGRAM_ID }}
          token_bot: ${{ secrets.TELEGRAM_TOKEN }}
